export { default as CommunicationIcon } from "./CommunicationIcon";
export { default as DashboardIcon } from "./DashboardIcon";
export { default as KYCIcon } from "./KYCIcon";
export { default as KYCIconCopy7 } from "./ImportIcon";
export { default as ExportIcon } from "./ExportIcon"
export { default as ImportIcon } from "./ImportIcon";
export { default as LoanIcon } from "./LoanIcon";
export { default as OverdueIcon } from "./OverdueIcon";
export { default as SubscriptionIcon } from "./SubscriptionIcon";
export { default as EmailIcon } from "./EmailIcon";
export { default as NotificationIcon } from "./NotificationIcon";
export { default as SmsIcon } from "./SMSIcon";
export { default as UserIcon } from "./UserIcon";
export { default as SendIcon } from "./SendIcon";
export { default as PlayStoreIcon } from "./PlayStoreIcon";
export { default as AppStoreIcon } from "./AppStoreIcon";
export { default as FlexiblePlanIcon } from "./FlexiblePlanIcon";
export { default as MoneyIcon } from "./MoneyIcon";
export { default as SecurityIcon } from "./SecurityIcon";
export { default as PhoneIcon } from "./PhoneIcon";
export { default as WithdrawalIcon } from "./WithdrawalIcon";
export { default as ReferralIcon } from "./ReferralIcon";
export { default as LogoutIcon } from "./LogoutIcon";
export { default as UserLockIcon } from "./UserLockIcon";
export { default as UserRemoveIcon } from "./UserRemoveIcon";

